#spring.application.name=newsfeed19
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}?characterEncoding=UTF-8
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    web:
      pageable:
        page-parameter: pageNumber
        size-parameter: pageSize

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    '[org.springframework.web]': DEBUG
    '[org.hibernate]': DEBUG